version: '3.7'

services:
  postgres:
    build:
      context: .
      dockerfile: ./files/postgres.Dockerfile
    image: postgres
    restart: always
    volumes:
      - ${HOST_PGDATA}/postgres:/var/lib/postgresql
    environment:
      - PGDATA="/var/lib/postgresql/data/pgdata"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  pgdata:
